### ISSUE TITLE
Errors on requests>2.13.0

### ISSUE THREAD

**Issue by dmitric** [phuslu/requests_httpsproxy#1]
There seems to be an error thrown when using versions of requests>2.13.0.

Here is the error trace I get:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/dlc/src/chargehound/testing/ch/scripts/test_proxy.py", line 34, in <module>
    proxies = proxies)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/adapters.py", line 403, in send
    conn = self.get_connection(request.url, proxies)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/adapters.py", line 302, in get_connection
    conn = proxy_manager.connection_from_url(url)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/packages/urllib3/poolmanager.py", line 279, in connection_from_url
    pool_kwargs=pool_kwargs)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/packages/urllib3/poolmanager.py", line 227, in connection_from_host
    return self.connection_from_context(request_context)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/packages/urllib3/poolmanager.py", line 238, in connection_from_context
    pool_key = pool_key_constructor(request_context)
  File "/Users/dlc/.virtualenvs/ch/lib/python2.7/site-packages/requests/packages/urllib3/poolmanager.py", line 103, in _default_key_normalizer
    return key_class(**context)
TypeError: __new__() got an unexpected keyword argument 'key__ssl_options'
```

Do you have any guidance on how to fix this to work with version 2.18.2? Do you know if this HTTPS Proxy problem still exists in requests?

**Comment by chocolatkey** [comment]
I have this problem as well!

**Comment by johnnybubonic** [comment]
same here, and yes the HTTPS proxy issue still occurs in upstream requests as well, @dmitric.

worth noting that if you have libcurl installed, [pycURL](http://pycurl.io/) works flawlessly with https proxies (because curl does).

**Comment by ikebo** [comment]
same issue, and if the requests version is 2.13.0, the result is:
``` python
ValueError: Caller provided invalid server host name: 112.74.108.33
```
the host name cannot  be ip address?
the https_proxy string I used like this: 
``` python
https_proxy = 'https://username:password@proxy_ip:proxy_port'
```

please handle this issue @phuslu

**Comment by hshe** [comment]
Version: 2.22.0
curl is ok but not requests
curl --proxy https://usename:password@hostname:port --proxy-insecure  http://httpbin.org/ip
requests.get('http://httpbin.org/ip',proxies={'http':  'https://usename:password@hostname:port '})

**Comment by distance00** [comment]
> same here, and yes the HTTPS proxy issue still occurs in upstream requests as well, @dmitric.
> 
> worth noting that if you have libcurl installed, [pycURL](http://pycurl.io/) works flawlessly with https proxies (because curl does) (as long as it was compiled with OpenSSL support. if it uses NSS instead, as it does on CentOS/RHEL and probably others, it probably won't - no idea on GnuTLS).

Im using "pycurl.CAINFO, certifi.where()" to solve the "SSL certificate problem", however, if I set a HTTPS proxy like this: "setopt(pycurl.PROXY, 'https://example.com:8080')", it appears again: "pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')". do I need to set a certificate for the HTTPS proxy? how?

**Comment by savandriy** [comment]
> > same here, and yes the HTTPS proxy issue still occurs in upstream requests as well, @dmitric.
> > worth noting that if you have libcurl installed, [pycURL](http://pycurl.io/) works flawlessly with https proxies (because curl does) (as long as it was compiled with OpenSSL support. if it uses NSS instead, as it does on CentOS/RHEL and probably others, it probably won't - no idea on GnuTLS).
> 
> Im using "pycurl.CAINFO, certifi.where()" to solve the "SSL certificate problem", however, if I set a HTTPS proxy like this: "setopt(pycurl.PROXY, 'https://example.com:8080')", it appears again: "pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')". do I need to set a certificate for the HTTPS proxy? how?

Hey, I managed to get pycurl working with the secure web proxies! I used this code to make a simple GET request:

```python
import pycurl
from io import BytesIO
import certifi


def request_with_pycurl(username, password, host, port, target_url='https://api.ipify.org/'):
    buffer = BytesIO()
    c = pycurl.Curl()

    c.setopt(pycurl.CAINFO, certifi.where())

    # set proxy-insecure
    c.setopt(c.PROXY_SSL_VERIFYHOST, 0)
    c.setopt(c.PROXY_SSL_VERIFYPEER, 0)

    # set headers
    c.setopt(pycurl.USERAGENT, 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0) Gecko/20100101 Firefox/8.0')

    # set proxy
    c.setopt(pycurl.PROXY, f"https://{host}:{port}")

    # proxy auth
    c.setopt(pycurl.PROXYUSERPWD, f"{username}:{password}")

    # set proxy type = "HTTPS
    c.setopt(pycurl.PROXYTYPE, 2)

    # target url
    c.setopt(c.URL, target_url)

    c.setopt(c.WRITEDATA, buffer)
    c.perform()
    c.close()

    body = buffer.getvalue()
    return body


response = request_with_pycurl("proxy_username", "proxy_password", "proxy_host", "proxy_port").decode()

print(response)

```

**Comment by distance00** [comment]
> > > same here, and yes the HTTPS proxy issue still occurs in upstream requests as well, @dmitric.
> > > worth noting that if you have libcurl installed, [pycURL](http://pycurl.io/) works flawlessly with https proxies (because curl does) (as long as it was compiled with OpenSSL support. if it uses NSS instead, as it does on CentOS/RHEL and probably others, it probably won't - no idea on GnuTLS).
> > 
> > 
> > Im using "pycurl.CAINFO, certifi.where()" to solve the "SSL certificate problem", however, if I set a HTTPS proxy like this: "setopt(pycurl.PROXY, 'https://example.com:8080')", it appears again: "pycurl.error: (60, 'SSL certificate problem: unable to get local issuer certificate')". do I need to set a certificate for the HTTPS proxy? how?
> 
> Hey, I managed to get pycurl working with the secure web proxies! I used this code to make a simple GET request:
> 
> ```python
> import pycurl
> from io import BytesIO
> import certifi
> 
> 
> def request_with_pycurl(username, password, host, port, target_url='https://api.ipify.org/'):
>     buffer = BytesIO()
>     c = pycurl.Curl()
> 
>     c.setopt(pycurl.CAINFO, certifi.where())
> 
>     # set proxy-insecure
>     c.setopt(c.PROXY_SSL_VERIFYHOST, 0)
>     c.setopt(c.PROXY_SSL_VERIFYPEER, 0)
> 
>     # set headers
>     c.setopt(pycurl.USERAGENT, 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:8.0) Gecko/20100101 Firefox/8.0')
> 
>     # set proxy
>     c.setopt(pycurl.PROXY, f"https://{host}:{port}")
> 
>     # proxy auth
>     c.setopt(pycurl.PROXYUSERPWD, f"{username}:{password}")
> 
>     # set proxy type = "HTTPS
>     c.setopt(pycurl.PROXYTYPE, 2)
> 
>     # target url
>     c.setopt(c.URL, target_url)
> 
>     c.setopt(c.WRITEDATA, buffer)
>     c.perform()
>     c.close()
> 
>     body = buffer.getvalue()
>     return body
> 
> 
> response = request_with_pycurl("proxy_username", "proxy_password", "proxy_host", "proxy_port").decode()
> 
> print(response)
> ```

Thanks! it worked. The magic word is "c.setopt(c.PROXY_SSL_VERIFYPEER, 0)", not even "c.setopt(pycurl.PROXYTYPE, 2)" is necessary. As long as the secure web proxy works with stunnel, it works here.  There are still some proxies working with Chrome, but not working with stunnel, they won't work here either. I guess the working ones are the "standard" ones?

**Comment by savandriy** [comment]
@dmitric @chocolatkey @johnnybubonic @ikebo @hshe with the latest pull requests, the library is fully functional! Worked for me on Python 2.7 & 3.7 on Windows & Ubuntu, worked well with gevent for async requests!
